ALTER TABLE vendors ADD COLUMN IF NOT EXISTS workspace CHARACTER VARYING;
ALTER TABLE vendors ADD COLUMN IF NOT EXISTS role CHARACTER VARYING;
ALTER TABLE vendors ALTER COLUMN account_type DROP NOT NULL;
